---
- name: Install Main Packages
  become: true
  apt:
    state: present
    pkg:
    - vim
    - curl
    - git
    - wget
    - tree
    - net-tools
    - apt-transport-https
    - zip 
    - unzip
    - build-essential
    - htop
    - btop
    - byobu
    - tmux
    - smartmontools
    - nmap
    - ethtool
    - etherwake
    - wakeonlan
    - sshfs
    - ncdu
    - mc
    - lm-sensors
    - cmake
    - sshpass
    - can-utils
    - net-tools
    - iperf3
    - tree
    - locate
 
- name: Download ASC key
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/usr/share/keyrings/microsoft.asc"
    mode: "0644"
        
- name: Add vscode repository into sources list
  apt_repository:
    repo: deb [arch=amd64, signed-by=/usr/share/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode

- name: Install vscode
  apt:
    name:
      - code
    state: latest
    update_cache: true

- name: Install GPG key for SubLimeText
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add specified repositories into sources list using specified filename
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present
    filename: "{{ item.file }}"
  with_items:
    - repo: https://download.sublimetext.com/
      add: apt/stable/
      file: sublime

- name: Install Other Packages
  become: true
  apt:
    state: present
    pkg:
    - ubuntu-restricted-extras
    - iotop
    - p7zip-full
    - unrar
    - python3-gpg
    - libssl-dev 
    - libusb-1.0-0-dev 
    - libudev-dev 
    - pkg-config 
    - libgtk-3-dev 
    - wireshark
    - traceroute
    - ffmpeg
    - terminator
    - nvtop
    - sublime-text
