---
- name: Install Main Packages
  become: true
  apt:
    state: present
    pkg:
    - vim
    - curl
    - git
    - wget
    - tree
    - net-tools
    - apt-transport-https
    - zip 
    - unzip
    - build-essential
    - htop
    - btop
    - byobu
    - tmux
    - smartmontools
    - nmap
    - ethtool
    - etherwake
    - wakeonlan
    - sshfs
    - ncdu
    - mc
    - lm-sensors
    - cmake
    - sshpass
    - can-utils
    - net-tools
    - iperf3
    - tree
    - locate

- name: Install GPG key for SubLimeText
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add specified repositories into sources list using specified filename
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present
    filename: "{{ item.file }}"
  with_items:
    - repo: https://download.sublimetext.com/
      add: apt/stable/
      file: sublime

- name: Install Other Packages
  become: true
  apt:
    state: present
    pkg:
    - ubuntu-restricted-extras
    - iotop
    - p7zip-full
    - unrar
    - python3-gpg
    - libssl-dev 
    - libusb-1.0-0-dev 
    - libudev-dev 
    - pkg-config 
    - libgtk-3-dev 
    - wireshark
    - traceroute
    - ffmpeg
    - terminator
    - nvtop
    - sublime-text