
---
- name: Install Other Packages
  become: true
  apt:
    state: present
    pkg:
    - iotop
    - p7zip-full
    - unrar
    - python3-gpg
    - libssl-dev 
    - libusb-1.0-0-dev 
    - libudev-dev 
    - pkg-config 
    - libgtk-3-dev 
    - wireshark
    - traceroute